language: cpp

compiler:
  - gcc

branches:
  only:
    - master
    - 2.0
    - 1.0

before_install:
  - sudo apt-get -y install zlib1g-dev libaspell-dev
  - sudo apt-get -y install qt5-default libqt5webkit5-dev

script:
  - ./build.linux.sh
